### PR TITLE
SPOTIFY_NAME changed on server

### PR DESCRIPTION
**Pull request by emiljoha**
Gave 404 file not found as new version of spotify.

Long term what is the to stop this happening over and over again?

### CODE REVIEW

**Comment by paolorotolo** [comment]
Hey, just noticed this PR. I already fixed the issue, there was another version of Spotify available.
Maybe we can make a script that scans the content of http://repository.spotify.com/pool/non-free/s/spotify-client/ and picks the package with higher version number.

**Comment by ghost** [comment]
I think yep

**Comment by ghost** [comment]
__Maybe__ i work on this feature, this afternoon.

**Comment by paolorotolo** [comment]
Awesome. Let's close this PR and move this discussion to an issue.
Can I assign #12 to you?

**Comment by ghost** [comment]
Yup!

**Pull request closed without merging**
